# Generated by Django 3.0.8 on 2020-07-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='people',
            field=models.IntegerField(default=2, verbose_name='人数'),
            preserve_default=False,
        ),
    ]
